remote_theme: just-the-docs/just-the-docs
search_enabled: true
title: Oceano Documentation
description: Oceano Documentation for user and developer
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://oceano.tk" # the base hostname & protocol for your site, e.g. http://example.com
